[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "dendrogenesis"
version = "0.1.0"
description = "dendrogenesis"
requires-python = ">=3.10"
license = { text = "MIT" }
dependencies = [
  "numpy",
  "matplotlib",
  "statsmodels",
  "pandas",
  "scipy",
  "tqdm",
  "seaborn",
  "piecewise-regression",
  "Jinja2",
  "statannotations",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
